# Generated by Django 4.2.7 on 2023-12-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_room_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
